// Secret-hunt codes. Students find or work out a code, redeem it on /chasse,
// and earn points (+ an optional badge). Edit here for the starting set, or
// manage live in the admin console (Secrets tab). The seed upserts on `code`,
// so re-running it corrects anything edited by hand in the admin.
//
// Three kinds of secret live in this list, and `location` says which:
//
//   "Devinette — …"      the hint is a riddle and the code is its answer.
//                        Nothing is hidden anywhere; the student just knows it.
//   "À IMPLÉMENTER — …"  the code is meant to be hidden in the site, and is not
//                        yet. The hint deliberately promises nothing.
//   "Connaissance — …"   the code names a real vulnerability that this site does
//                        NOT have and must never be given. ==Do not "implement"
//                        these== — the point is to recognise the attack, not to
//                        make a school site injectable so a student can score.
//   "Palier automatique" granted by lib/milestones.ts when a student reaches
//                        `unlockAt` non-milestone secrets. Typing it is refused.
//
// `location` is admin-only and is shown to a student only after they find it;
// `hint` is the public clue on the hunt board.

export type SecretDifficulty = "easy" | "medium" | "hard" | "insane"

export interface SecretSeed {
  code: string
  name: string
  hint: string
  location: string
  points: number
  category: string
  difficulty: SecretDifficulty
  badgeSlug?: string
  /**
   * Number of NON-milestone secrets a student must have found for this one to
   * be granted automatically. `undefined` for an ordinary secret.
   *
   * The final milestone's value is the count of ordinary secrets, so adding an
   * ordinary secret without bumping it would make the "find everything" reward
   * fire one secret early. tests/secret-seeds.test.ts asserts the two match.
   */
  unlockAt?: number
}

export const SECRET_SEEDS: SecretSeed[] = [
  {
    code: "1984-ORWELL",
    name: "Livre dystopie 1984",
    hint: "Big Brother. Totalitarisme. Dystopie.",
    location: "Devinette — la réponse est le code",
    points: 15,
    category: "BOOKS",
    difficulty: "medium",
  },
  {
    code: "2FA-TOTP",
    name: "Authentification deux facteurs",
    hint: "Google Authenticator. Code temporaire.",
    location: "Devinette — la réponse est le code",
    points: 20,
    category: "CYBERSECURITY",
    difficulty: "medium",
  },
  {
    code: "ACHERON",
    name: "Personnage de la Nihilité du jeu Honkai Star Rail",
    hint: "Honkai, nihilité, elle tue.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "GAMING-ANIME",
    difficulty: "medium",
  },
  {
    code: "ALPHAZERO-CHESS",
    name: "Jeu échecs AlphaZero IA",
    hint: "Deep Mind. Self-play. Surhumain.",
    location: "Devinette — la réponse est le code",
    points: 25,
    category: "AI-GAMING",
    difficulty: "hard",
  },
  {
    code: "AMONG-US-SUS",
    name: "Meme Among Us sus",
    hint: "Red is sus. Imposteur.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "INTERNET-MEMES",
    difficulty: "easy",
  },
  {
    code: "ANONYMOUS",
    name: "Hackers légendaires",
    hint: "Guy Fawkes masks. Hacktivist.",
    location: "Devinette — la réponse est le code",
    points: 20,
    category: "HACKING-HISTORY",
    difficulty: "medium",
  },
  {
    code: "ASTEROID-DINO",
    name: "Astéroïde dans l'espace",
    hint: "K-T extinction. Dinosaures disparus.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "SCIENCE",
    difficulty: "easy",
  },
  {
    code: "ATTACK-ON-TITAN",
    name: "Anime avec des titans",
    hint: "Shingeki no Kyojin.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "ANIME",
    difficulty: "easy",
  },
  {
    code: "AVENGERS-RUSSO",
    name: "Directeur des Avengers Russo",
    hint: "Deux frères. Réalisateurs légendaires.",
    location: "Devinette — la réponse est le code",
    points: 15,
    category: "MOVIES",
    difficulty: "medium",
  },
  {
    code: "BANE",
    name: "The Dark Knight rises le villain",
    hint: "You merely adopted the dark.",
    location: "Devinette — la réponse est le code",
    points: 12,
    category: "MOVIES",
    difficulty: "easy",
  },
  {
    code: "BATMAN-ARKHAM",
    name: "Batman Arkham",
    hint: "Arkham City, Asylum.",
    location: "Devinette — la réponse est le code",
    points: 15,
    category: "GAMING",
    difficulty: "medium",
  },
  {
    code: "BEETHOVEN",
    name: "Compositeur sourd génial",
    hint: "9e symphonie. Symphonie inaudible.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "MUSIC-HISTORY",
    difficulty: "easy",
  },
  {
    code: "BILLIE-EILISH",
    name: "Musicienne pop blond",
    hint: "Bad guy. Jeune. Whisper vocal.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "MUSIC",
    difficulty: "easy",
  },
  {
    code: "BLACK-HOLE",
    name: "Trou noir gravité limite",
    hint: "Event horizon. Singularité.",
    location: "Devinette — la réponse est le code",
    points: 15,
    category: "ASTRONOMY",
    difficulty: "medium",
  },
  {
    code: "BLOCKCHAIN-POW",
    name: "Concept blockchain mining",
    hint: "Preuve de travail. Mineur.",
    location: "Devinette — la réponse est le code",
    points: 25,
    category: "TECH",
    difficulty: "hard",
  },
  {
    code: "BRAVE-NEW-WORLD",
    name: "Dystopie Brave New World",
    hint: "Aldous Huxley. Bonheur controlé.",
    location: "Devinette — la réponse est le code",
    points: 15,
    category: "BOOKS",
    difficulty: "medium",
  },
  {
    code: "C64-PROGRAMMER",
    name: "Programmeur du Commodore 64",
    hint: "Atari, premiers jeux, 8-bit.",
    location: "Devinette — la réponse est le code",
    points: 15,
    category: "TECH-HISTORY",
    difficulty: "medium",
  },
  {
    code: "CHICKEN-JOKE",
    name: "Pourquoi la poule traverse la route",
    hint: "Blague classique. De l'autre côté.",
    location: "Devinette — la réponse est le code",
    points: 8,
    category: "JOKES",
    difficulty: "easy",
  },
  {
    code: "CICD-PIPELINE",
    name: "CI/CD pipeline automation",
    hint: "Jenkins. GitLab. Automatisation.",
    location: "Devinette — la réponse est le code",
    points: 25,
    category: "DEVOPS",
    difficulty: "hard",
  },
  {
    code: "CIVILIZATION",
    name: "Jeu stratégie tour au tour",
    hint: "Sid Meier. Construction empire.",
    location: "Devinette — la réponse est le code",
    points: 15,
    category: "GAMING",
    difficulty: "medium",
  },
  {
    code: "CRYPTOLOCKER",
    name: "Ransomware cryptolocker",
    hint: "2013. Chiffrement fichiers rançon.",
    location: "Devinette — la réponse est le code",
    points: 25,
    category: "CYBERSECURITY",
    difficulty: "hard",
  },
  {
    code: "DDOS-FLOOD",
    name: "DDoS attack flooding",
    hint: "Déni de service. Saturation serveur.",
    location: "Devinette — la réponse est le code",
    points: 25,
    category: "CYBERSECURITY",
    difficulty: "hard",
  },
  {
    code: "DEATH-NOTE",
    name: "Anime psychologique Death Note",
    hint: "Cahier noir. Noms. Light Yagami.",
    location: "Devinette — la réponse est le code",
    points: 15,
    category: "ANIME",
    difficulty: "medium",
  },
  {
    code: "DESTINY2",
    name: "Eyes Up Guardian",
    hint: "Un jeu de tir sci-fi avec des Gardiens.",
    location: "Devinette — la réponse est le code",
    points: 20,
    category: "GAMING",
    difficulty: "hard",
  },
  {
    code: "DICAPRIO",
    name: "Acteur Dicaprio jeune",
    hint: "Titanic. Inception. Bel homme.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "MOVIES",
    difficulty: "easy",
  },
  {
    code: "DIGITAL-RAIN",
    name: "The Matrix code rain",
    hint: "Caractères verts tombant. Iconic.",
    location: "Devinette — la réponse est le code",
    points: 12,
    category: "MOVIES-AESTHETIC",
    difficulty: "easy",
  },
  {
    code: "DISTRACTED-BF",
    name: "Meme distracted boyfriend",
    hint: "Garçon regarde autre fille.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "INTERNET-MEMES",
    difficulty: "easy",
  },
  {
    code: "DOCKER",
    name: "Conteneur Docker magical",
    hint: "Works on my machine devient vrai.",
    location: "Devinette — la réponse est le code",
    points: 15,
    category: "DEVOPS",
    difficulty: "medium",
  },
  {
    code: "DOGE-SHIBE",
    name: "Meme du Doge",
    hint: "Much wow. Very meme. So internet.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "INTERNET-MEMES",
    difficulty: "easy",
  },
  {
    code: "DRAKE-MEME",
    name: "Meme Drake réaction",
    hint: "Pas bien. Très bien. Haut bas.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "INTERNET-MEMES",
    difficulty: "easy",
  },
  {
    code: "DUNE-FRANK",
    name: "Roman science-fiction Dune",
    hint: "Épices. Désert. Politiques.",
    location: "Devinette — la réponse est le code",
    points: 15,
    category: "BOOKS",
    difficulty: "medium",
  },
  {
    code: "E-MC2",
    name: "Équation célèbre Einstein",
    hint: "Énergie = Masse × Vitesse².",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "SCIENCE",
    difficulty: "easy",
  },
  {
    code: "EIICHIRO-ODA",
    name: "Mangaka d'One Piece",
    hint: "Pirate, trésor, aventure infinie.",
    location: "Devinette — la réponse est le code",
    points: 15,
    category: "MANGA-CREATORS",
    difficulty: "medium",
  },
  {
    code: "EINSTEIN",
    name: "Scientifique avec cheveux fous",
    hint: "E=mc². Génie foufou.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "HISTORY",
    difficulty: "easy",
  },
  {
    code: "ELDEN-RING",
    name: "Jeu Elden Ring difficile",
    hint: "FromSoftware. Souls-like. Difficile.",
    location: "Devinette — la réponse est le code",
    points: 15,
    category: "GAMING",
    difficulty: "medium",
  },
  {
    code: "ELSA",
    name: "La reine des neiges",
    hint: "Let it go. Libérée, délivrée.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "MOVIES",
    difficulty: "easy",
  },
  {
    code: "EMINEM",
    name: "Rappeur légendaire Eminem",
    hint: "Slim Shady. Rap rapide. Blanc.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "MUSIC",
    difficulty: "easy",
  },
  {
    code: "ETHEREUM-SMART",
    name: "Cryptocurrency Ethereum",
    hint: "Vitalik Buterin. Contrats intelligents.",
    location: "Devinette — la réponse est le code",
    points: 15,
    category: "TECH",
    difficulty: "medium",
  },
  {
    code: "FACEBOOK",
    name: "Réseau social face",
    hint: "Meta. Zuckerberg. Données.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "TECH",
    difficulty: "easy",
  },
  {
    code: "FAUST",
    name: "Pact avec le diable faust",
    hint: "Légende allemande. Pouvoir vs âme.",
    location: "Devinette — la réponse est le code",
    points: 15,
    category: "LITERATURE",
    difficulty: "medium",
  },
  {
    code: "FIREWALL-RULES",
    name: "Firewall pare-feu réseau",
    hint: "Pare-feu. Ports. Règles trafic.",
    location: "Devinette — la réponse est le code",
    points: 20,
    category: "CYBERSECURITY",
    difficulty: "medium",
  },
  {
    code: "FORTNITE",
    name: "Je suis un FPS pour enfants",
    hint: "Nes créateurs font beaucoup trop de collabs.",
    location: "Devinette — la réponse est le code",
    points: 9,
    category: "GAMING",
    difficulty: "easy",
  },
  {
    code: "FORTNITE-BATTLE-PASS",
    name: "Battle royale île tempête",
    hint: "100 joueurs. Skin cosmétique.",
    location: "Devinette — la réponse est le code",
    points: 15,
    category: "GAMING",
    difficulty: "medium",
  },
  {
    code: "FRIENDS-TV",
    name: "Série Friends café central",
    hint: "Six amis. New York. Phoebe.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "TV",
    difficulty: "easy",
  },
  {
    code: "GAME-OF-THRONES",
    name: "Game of Thrones Winter is Coming",
    hint: "Dragons, Trônes, Saisons interminables.",
    location: "Devinette — la réponse est le code",
    points: 12,
    category: "TV",
    difficulty: "easy",
  },
  {
    code: "GIGACHAD",
    name: "Meme Giga Chad sigma male",
    hint: "Mentonat. Énorme. Basé.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "INTERNET-MEMES",
    difficulty: "easy",
  },
  {
    code: "GODADDY-HACK",
    name: "Passe-partout GoDaddy",
    hint: "2021 breach. Registrar compromis.",
    location: "Devinette — la réponse est le code",
    points: 25,
    category: "CYBERSECURITY-HISTORY",
    difficulty: "hard",
  },
  {
    code: "GOKU",
    name: "Le personnage qui sauve l'univers Dragon Ball",
    hint: "Kamehameha !",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "ANIME",
    difficulty: "easy",
  },
  {
    code: "GOOGLE-SEARCH",
    name: "Moteur recherche spider",
    hint: "Web crawler. PageRank. Publicité.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "TECH",
    difficulty: "easy",
  },
  {
    code: "GPL-LICENSE",
    name: "GPL copyleft obligation",
    hint: "Source accessible. Dérivés libres.",
    location: "Devinette — la réponse est le code",
    points: 15,
    category: "TECH",
    difficulty: "medium",
  },
  {
    code: "GRAPHQL-QUERY",
    name: "GraphQL requête flexible",
    hint: "Facebook. Requête données précises.",
    location: "Devinette — la réponse est le code",
    points: 15,
    category: "PROGRAMMING",
    difficulty: "medium",
  },
  {
    code: "GRUMPY-CAT",
    name: "Meme Grumpy Cat",
    hint: "I hate you all.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "INTERNET-MEMES",
    difficulty: "easy",
  },
  {
    code: "HARRY-POTTER",
    name: "Harry Potter à l'école",
    hint: "Magie, baguettes, Hogwarts.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "BOOKS",
    difficulty: "easy",
  },
  {
    code: "HIGGS-BOSON",
    name: "Particule élémentaire boson",
    hint: "Masse. CERN. Dieu particulaire.",
    location: "Devinette — la réponse est le code",
    points: 25,
    category: "PHYSICS",
    difficulty: "hard",
  },
  {
    code: "HIMYM",
    name: "Sitcom How I Met Mother",
    hint: "Ted Mosby. Mère. Fin controversée.",
    location: "Devinette — la réponse est le code",
    points: 15,
    category: "TV",
    difficulty: "medium",
  },
  {
    code: "HOLLOW-KNIGHT",
    name: "Jeu Hollow Knight indie",
    hint: "Chevalier. Royaume creux. 2D.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "GAMING",
    difficulty: "easy",
  },
  {
    code: "HTTPS-SSL",
    name: "Protocole sécurité HTTPS",
    hint: "Certificat. Chiffrement. Cadenas.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "CYBERSECURITY",
    difficulty: "easy",
  },
  {
    code: "IDRIS",
    name: "Mot de passe oublié",
    hint: "Je suis le premier à avoir oublié mon mot de passe.",
    location: "Devinette — la réponse est le code",
    points: 20,
    category: "SECURITY",
    difficulty: "medium",
  },
  {
    code: "INCEPTION",
    name: "Inception rêves imbriqués",
    hint: "Quel niveau de rêve sommes-nous ?",
    location: "Devinette — la réponse est le code",
    points: 20,
    category: "MOVIES",
    difficulty: "hard",
  },
  {
    code: "IRONMAN",
    name: "Avenger noir et jaune",
    hint: "Tony Stark. Armure Tech. JARVIS.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "COMICS-MOVIES",
    difficulty: "easy",
  },
  {
    code: "KEVIN-MITNICK",
    name: "Hacker célèbre lunettes",
    hint: "Phone hacker. Social engineering.",
    location: "Devinette — la réponse est le code",
    points: 20,
    category: "HACKING-HISTORY",
    difficulty: "medium",
  },
  {
    code: "KUBERNETES",
    name: "Kubernetes container orchestration",
    hint: "K8s. Auto-scaling. Production.",
    location: "Devinette — la réponse est le code",
    points: 25,
    category: "DEVOPS",
    difficulty: "hard",
  },
  {
    code: "LINK",
    name: "Le héros de Zelda",
    hint: "Verte tunique. Ne parle jamais.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "GAMING",
    difficulty: "easy",
  },
  {
    code: "LINUX",
    name: "Distro Linux pinguin",
    hint: "Tux. Open source. Libre.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "TECH",
    difficulty: "easy",
  },
  {
    code: "LOSS-MEME",
    name: "Meme Loss référence",
    hint: "Quatre bandes. Trois debout. Un couché.",
    location: "Devinette — la réponse est le code",
    points: 25,
    category: "INTERNET-MEMES",
    difficulty: "hard",
  },
  {
    code: "MATRIX",
    name: "Matrix codes",
    hint: "Matrice. Monde virtuel. Pastille rouge.",
    location: "Devinette — la réponse est le code",
    points: 15,
    category: "MOVIES",
    difficulty: "easy",
  },
  {
    code: "MICROSERVICES",
    name: "Microservices architecture",
    hint: "Services indépendants. Scalabilité.",
    location: "Devinette — la réponse est le code",
    points: 25,
    category: "DEVOPS",
    difficulty: "hard",
  },
  {
    code: "MIT-LICENSE",
    name: "Licence logiciel MIT libre",
    hint: "Très permissif. Gratuit. Code ouvert.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "TECH",
    difficulty: "easy",
  },
  {
    code: "MITM-ATTACK",
    name: "Man-in-the-middle attack",
    hint: "Interception réseau. Écoute active.",
    location: "Devinette — la réponse est le code",
    points: 25,
    category: "CYBERSECURITY",
    difficulty: "hard",
  },
  {
    code: "MONGODB",
    name: "Base de données NoSQL",
    hint: "JSON, flexible, scalable.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "PROGRAMMING",
    difficulty: "easy",
  },
  {
    code: "MOSAIC-NETSCAPE",
    name: "Le premier navigateur web",
    hint: "1990s. Avant Internet Explorer.",
    location: "Devinette — la réponse est le code",
    points: 15,
    category: "WEB-HISTORY",
    difficulty: "medium",
  },
  {
    code: "NARUTO",
    name: "Manga de ninjas",
    hint: "Shinobi, chakra, amitié.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "ANIME-MANGA",
    difficulty: "easy",
  },
  {
    code: "NEURAL-NETWORKS",
    name: "Machine learning neural networks",
    hint: "Deep learning. TensorFlow.",
    location: "Devinette — la réponse est le code",
    points: 25,
    category: "AI",
    difficulty: "hard",
  },
  {
    code: "NEVER-GONNA-GIVE",
    name: "Chanson Rickroll URL",
    hint: "1987 hit. Rick Astley.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "INTERNET-CULTURE",
    difficulty: "easy",
  },
  {
    code: "NICE-NUMBER",
    name: "Number 69 nice",
    hint: "Nice.",
    location: "Devinette — la réponse est le code",
    points: 69,
    category: "INTERNET-MEMES",
    difficulty: "easy",
  },
  {
    code: "NIGHTCORE",
    name: "Type de musique speedrun",
    hint: "Chanson accélérée avec voix aiguë. C'est un meme.",
    location: "Devinette — la réponse est le code",
    points: 15,
    category: "MUSIC",
    difficulty: "easy",
  },
  {
    code: "NLP-TRANSFORMERS",
    name: "NLP natural language processing",
    hint: "BERT. GPT. Langage naturel.",
    location: "Devinette — la réponse est le code",
    points: 25,
    category: "AI",
    difficulty: "hard",
  },
  {
    code: "NOTCH-MINECRAFT",
    name: "Le Createur de Minecraft",
    hint: "Blocs. Infini. Créativité sandbox.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "GAMING-CREATORS",
    difficulty: "easy",
  },
  {
    code: "ONE-RING",
    name: "L'arme de destruction du Seigneur des Anneaux",
    hint: "Un anneau pour les gouverner tous.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "MOVIES-BOOKS",
    difficulty: "easy",
  },
  {
    code: "OWASP-INJECTION",
    name: "OWASP Top 10 injection",
    hint: "Injection SQL, NoSQL, LDAP.",
    location: "Devinette — la réponse est le code",
    points: 25,
    category: "CYBERSECURITY",
    difficulty: "hard",
  },
  {
    code: "PEWDIEPIE",
    name: "Youtuber gaming furieux",
    hint: "Felix. Suédois. Minecraft gaming.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "YOUTUBERS",
    difficulty: "easy",
  },
  {
    code: "PHISHING-SCAM",
    name: "Phishing mail faux",
    hint: "Email imposteur. Vol credentials.",
    location: "Devinette — la réponse est le code",
    points: 15,
    category: "CYBERSECURITY",
    difficulty: "easy",
  },
  {
    code: "PLATO-CAVE",
    name: "Philosophe cave allégorie",
    hint: "Ombres. Réalité. Illusion.",
    location: "Devinette — la réponse est le code",
    points: 25,
    category: "PHILOSOPHY",
    difficulty: "hard",
  },
  {
    code: "POKIMANE",
    name: "Streamer esport extrême",
    hint: "League of Legends. Twitch reine.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "STREAMERS",
    difficulty: "easy",
  },
  {
    code: "PYTHON",
    name: "Langage de programmation serpent",
    hint: "Snake. Guido van Rossum.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "PROGRAMMING",
    difficulty: "easy",
  },
  {
    code: "RAGE-FACE",
    name: "Le gros meme 2010",
    hint: "FUUUUU—————",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "INTERNET-MEMES",
    difficulty: "easy",
  },
  {
    code: "REACT",
    name: "Framework web Javascript",
    hint: "Facebook, composants, state.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "PROGRAMMING",
    difficulty: "easy",
  },
  {
    code: "RECAPTCHA",
    name: "CAPTCHA robot verification",
    hint: "Je ne suis pas un robot.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "SECURITY",
    difficulty: "easy",
  },
  {
    code: "REST-API",
    name: "Protocole REST API web",
    hint: "GET, POST, PUT, DELETE.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "PROGRAMMING",
    difficulty: "easy",
  },
  {
    code: "RICKROLL",
    name: "Rickroll classique",
    hint: "Never gonna give you up.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "INTERNET-MEMES",
    difficulty: "easy",
  },
  {
    code: "RUBIKS-ANIME",
    name: "Anime cubes colorés",
    hint: "Cubes de Rubik années 90.",
    location: "Devinette — la réponse est le code",
    points: 12,
    category: "ANIME",
    difficulty: "medium",
  },
  {
    code: "SATOSHI-NAKAMOTO",
    name: "Créateur de Bitcoin",
    hint: "Crypto, blockchain, mystérieux.",
    location: "Devinette — la réponse est le code",
    points: 25,
    category: "TECH",
    difficulty: "hard",
  },
  {
    code: "SCP-FOUNDATION",
    name: "Mystère SCP containment",
    hint: "Objets surnaturels. Confinement secret.",
    location: "Devinette — la réponse est le code",
    points: 20,
    category: "INTERNET-HORROR",
    difficulty: "medium",
  },
  {
    code: "SHERLOCK",
    name: "Sherlock Holmes detective",
    hint: "Elementary, my dear Watson.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "BOOKS-TV",
    difficulty: "easy",
  },
  {
    code: "SIN-404",
    name: "Perdu mais pas pour tout le monde",
    hint: "Que se passe-t-il si tu demandes une page qui n'existe pas ?",
    location: "Page 404 personnalisée",
    points: 15,
    category: "WEB",
    difficulty: "easy",
  },
  {
    code: "SIN-ADMIN",
    name: "La page secrète /admin",
    hint: "Certains chemins d'URL sont tellement prévisibles qu'on les essaie en premier.",
    location: "À IMPLÉMENTER — cacher le code sur une page au chemin prévisible",
    points: 25,
    category: "WEB",
    difficulty: "hard",
  },
  {
    code: "SIN-API-KEY-HARDCODED",
    name: "API key en dur",
    hint: "Une clé d'API écrite en dur dans le code d'une page est lisible par tout le monde. C'est une des fautes les plus courantes.",
    location: "À IMPLÉMENTER — fausse clé (jamais une vraie) dans un commentaire JS",
    points: 25,
    category: "CYBERSECURITY",
    difficulty: "hard",
  },
  {
    code: "SIN-BACKUP-FILE",
    name: "Backup .bak oublié",
    hint: "Un fichier de sauvegarde oublié à côté de l'original garde en général tout son contenu.",
    location: "À IMPLÉMENTER — fichier .bak leurre ne contenant que le code",
    points: 35,
    category: "CYBERSECURITY",
    difficulty: "insane",
  },
  {
    code: "SIN-BASE64-DECODE",
    name: "Décode-moi Base64",
    hint: "Le Base64 n'est pas du chiffrement, seulement un encodage. N'importe quel décodeur en ligne suffit à le lire.",
    location: "À IMPLÉMENTER — chaîne base64 à placer dans une page",
    points: 20,
    category: "ENCODING",
    difficulty: "medium",
  },
  {
    code: "SIN-CONSOLE",
    name: "Message dans la console",
    hint: "Les navigateurs ont une console pour les développeurs. Ouvre-la (F12) et lis bien.",
    location: "console.log au chargement du site",
    points: 20,
    category: "WEB",
    difficulty: "easy",
  },
  {
    code: "SIN-CSS-DISPLAY-NONE",
    name: "Cache-cache CSS display none",
    hint: "Le CSS sait rendre un texte invisible sans le supprimer. Sélectionne toute la page pour t'en convaincre.",
    location: "À IMPLÉMENTER — texte masqué en CSS",
    points: 25,
    category: "WEB",
    difficulty: "hard",
  },
  {
    code: "SIN-DEBUG-PARAM",
    name: "Paramètre debug true secret",
    hint: "Un paramètre d'URL oublié en production peut en dire beaucoup trop.",
    location: "Page /vie (jeu de la vie) — panneau de debug affiché par ?debug=true",
    points: 25,
    category: "WEB",
    difficulty: "hard",
  },
  {
    code: "SIN-DOCKER-ENV",
    name: "Configuration Docker exposée",
    hint: "Le fichier qui porte les variables d'environnement d'un conteneur, mots de passe compris. Il ne doit jamais être servi par le web.",
    location: "Connaissance — la faille n'existe pas ici et ne doit jamais être créée",
    points: 25,
    category: "CYBERSECURITY",
    difficulty: "hard",
  },
  {
    code: "SIN-GIT-EXPOSED",
    name: "Dossier Git exposé",
    hint: "Quand un serveur laisse traîner son dossier de versionnement à la racine, tout l'historique du code devient public. Ce site ne le fait pas — beaucoup le font.",
    location: "Connaissance — la faille n'existe pas ici et ne doit jamais être créée",
    points: 40,
    category: "CYBERSECURITY",
    difficulty: "insane",
  },
  {
    code: "SIN-HEADER-CUSTOM",
    name: "Headers HTTP secrets",
    hint: "Une réponse HTTP ne contient pas que la page : elle transporte aussi des en-têtes que le navigateur ne montre pas.",
    location: "À IMPLÉMENTER — en-tête de réponse X-Custom-Secret",
    points: 25,
    category: "CYBERSECURITY",
    difficulty: "hard",
  },
  {
    code: "SIN-JWT-DECODE",
    name: "JWT token decodé",
    hint: "Un JWT n'est pas chiffré : sa charge utile est du Base64 que n'importe qui peut lire. La signature protège l'intégrité, pas le secret.",
    location: "À IMPLÉMENTER — JWT de démonstration à décoder",
    points: 25,
    category: "CYBERSECURITY",
    difficulty: "hard",
  },
  {
    code: "SIN-KONAMI",
    name: "Le code Konami",
    hint: "Les vieux joueurs connaissent la combinaison magique. Essaie-la sur la page d'accueil.",
    location: "Accueil : séquence clavier ↑ ↑ ↓ ↓ ← → ← → B A",
    points: 30,
    category: "EASTER-EGG",
    difficulty: "hard",
    badgeSlug: "secret",
  },
  {
    code: "SIN-LOCALSTORAGE-HACK",
    name: "LocalStorage infiltration admin",
    hint: "Le navigateur garde des données pour chaque site. Outils de développement, onglet Application, Local Storage.",
    location: "À IMPLÉMENTER — clé leurre dans localStorage",
    points: 20,
    category: "WEB",
    difficulty: "medium",
  },
  {
    code: "SIN-NETWORK-SPY",
    name: "Requête réseau suspecte",
    hint: "L'onglet Réseau des outils de développement montre tout ce qu'une page demande vraiment, pas seulement ce qu'elle affiche.",
    location: "À IMPLÉMENTER — requête leurre visible dans l'onglet Réseau",
    points: 25,
    category: "CYBERSECURITY",
    difficulty: "hard",
  },
  {
    code: "SIN-PATH-TRAVERSAL",
    name: "Chemin traversal passwd",
    hint: "Remonter l'arborescence à coups de points-points jusqu'à un fichier qu'on ne devrait pas pouvoir lire. Ne l'essaie pas ici.",
    location: "Connaissance — la faille n'existe pas ici et ne doit jamais être créée",
    points: 50,
    category: "CYBERSECURITY",
    difficulty: "insane",
  },
  {
    code: "SIN-PROF",
    name: "La page secrète",
    hint: "Il paraît qu'une page cachée existe. Son adresse ressemble à un mot que les espions adorent.",
    location: "/secret",
    points: 25,
    category: "WEB",
    difficulty: "medium",
    badgeSlug: "secret",
  },
  {
    code: "SIN-ROBOTS",
    name: "Robots autorisés",
    hint: "Un fichier standard indique aux moteurs de recherche où ne pas aller. Va y jeter un œil.",
    location: "/robots.txt (commentaire)",
    points: 15,
    category: "CYBERSECURITY",
    difficulty: "easy",
  },
  {
    code: "SIN-SERVICE-WORKER-EVIL",
    name: "Service Worker malveillant",
    hint: "Un script qui s'installe dans le navigateur et sert le contenu à la place du serveur. Précieux pour le hors-ligne, redoutable s'il est détourné.",
    location: "Connaissance — la faille n'existe pas ici et ne doit jamais être créée",
    points: 40,
    category: "CYBERSECURITY",
    difficulty: "insane",
  },
  {
    code: "SIN-SOURCE",
    name: "Vue sur la source",
    hint: "Les développeurs regardent toujours sous le capot. Que cache le code d'une page ?",
    location: "Commentaire HTML caché dans le <head> du site",
    points: 15,
    category: "WEB",
    difficulty: "easy",
    badgeSlug: "secret",
  },
  {
    code: "SIN-SQL-INJECT",
    name: "Hack SQL injection",
    hint: "Glisser une apostrophe dans un formulaire pour que la base lise du code là où elle attendait une donnée. La parade tient en deux mots : requêtes paramétrées. Ne l'essaie pas ici.",
    location: "Connaissance — la faille n'existe pas ici et ne doit jamais être créée",
    points: 50,
    category: "CYBERSECURITY",
    difficulty: "insane",
  },
  {
    code: "SIN-SSH-KEY",
    name: "Clé privée SSH exposée",
    hint: "La moitié privée d'une paire de clés ne quitte jamais ta machine. Si elle finit dans un dépôt, elle est brûlée : on la remplace, on ne la cache pas.",
    location: "Connaissance — aucune vraie clé n'existe sur ce site",
    points: 45,
    category: "CYBERSECURITY",
    difficulty: "insane",
  },
  {
    code: "SIN-TERMINAL",
    name: "L'invité du terminal",
    hint: "Dans le terminal, une commande peu connue révèle un message. Tape « secret ».",
    location: "Terminal : commande `secret`",
    points: 20,
    category: "HACKING",
    difficulty: "hard",
  },
  {
    code: "SIN-TIMING-TRAP",
    name: "Timing parfait minuit",
    hint: "Certaines choses ne se montrent qu'à une heure très précise.",
    location: "À IMPLÉMENTER — élément affiché uniquement à minuit",
    points: 35,
    category: "HACKING",
    difficulty: "insane",
  },
  {
    code: "SIN-WEAK-PASSWORD",
    name: "Password123 réutilisé",
    hint: "Le couple identifiant/mot de passe qu'un attaquant essaie en tout premier, parce qu'il fonctionne encore beaucoup trop souvent.",
    location: "Connaissance — aucun compte faible ici",
    points: 15,
    category: "CYBERSECURITY",
    difficulty: "medium",
  },
  {
    code: "SIN-ZERO-WIDTH",
    name: "Caractères invisibles Unicode",
    hint: "Unicode contient des caractères de largeur nulle : invisibles à l'œil, bien présents au copier-coller.",
    location: "À IMPLÉMENTER — espaces zéro-largeur encodant le code",
    points: 25,
    category: "ENCODING",
    difficulty: "hard",
  },
  {
    code: "SLENDERMAN",
    name: "Creepypasta Slenderman",
    hint: "Pas de visage. Suit les enfants.",
    location: "Devinette — la réponse est le code",
    points: 25,
    category: "INTERNET-HORROR",
    difficulty: "hard",
  },
  {
    code: "SMARTCONTRACT",
    name: "Smart contract Ethereum",
    hint: "Code auto-exécutable blockchain.",
    location: "Devinette — la réponse est le code",
    points: 25,
    category: "TECH",
    difficulty: "hard",
  },
  {
    code: "SPEC-OPS-LINE",
    name: "WAS IT WORTH IT",
    hint: "Spec Ops: The Line. Noir et déprimant.",
    location: "Devinette — la réponse est le code",
    points: 20,
    category: "GAMING",
    difficulty: "hard",
  },
  {
    code: "SPIDERMAN-MEME",
    name: "Meme Spider-man pointer",
    hint: "Deux Spider-mans pointent.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "INTERNET-MEMES",
    difficulty: "easy",
  },
  {
    code: "SPONGEBOB-GAME",
    name: "Platformer avec éponge",
    hint: "Bikini Bottom. Perle. Jeu PS1.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "GAMING",
    difficulty: "easy",
  },
  {
    code: "SQUEEZIE",
    name: "Youtubeur gaming français",
    hint: "CyRide, Minecraft, viral.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "YOUTUBERS",
    difficulty: "easy",
  },
  {
    code: "SQUID-GAME",
    name: "Battaille royale Squid Game",
    hint: "Survie. Jeux enfantins. Coréen.",
    location: "Devinette — la réponse est le code",
    points: 15,
    category: "TV",
    difficulty: "medium",
  },
  {
    code: "SSH-PROTOCOL",
    name: "Protocole SSH sécurité",
    hint: "Port 22. Remote secure shell.",
    location: "Devinette — la réponse est le code",
    points: 20,
    category: "CYBERSECURITY",
    difficulty: "medium",
  },
  {
    code: "STEVE-JOBS",
    name: "Fondateur Apple fruité",
    hint: "Pomme croquée. Design. Minimalisme.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "TECH-PEOPLE",
    difficulty: "easy",
  },
  {
    code: "SUPERMAN",
    name: "Héros DC alien bleu",
    hint: "Krypton. Cape rouge. Invulnérable.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "COMICS",
    difficulty: "easy",
  },
  {
    code: "TARANTINO",
    name: "Réalisateur Tarantino dialogue",
    hint: "Pulp Fiction. Dialogue. Pieds.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "MOVIES",
    difficulty: "easy",
  },
  {
    code: "TERRAFORM-IAC",
    name: "Infrastructure as Code IaC",
    hint: "Terraform. Infra codée.",
    location: "Devinette — la réponse est le code",
    points: 20,
    category: "DEVOPS",
    difficulty: "medium",
  },
  {
    code: "THANOS-INFINITY",
    name: "Le plan de Thanos",
    hint: "Avec un clic. Mais à quel prix ?",
    location: "Devinette — la réponse est le code",
    points: 15,
    category: "MOVIES",
    difficulty: "easy",
  },
  {
    code: "THEOFFICE",
    name: "Série The Office mockumentary",
    hint: "Bureau. Humour gêne. Mockumentaire.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "TV",
    difficulty: "easy",
  },
  {
    code: "TROJAN-MALWARE",
    name: "Malware Trojan horse",
    hint: "Cheval Troie. Infecte discrètement.",
    location: "Devinette — la réponse est le code",
    points: 20,
    category: "CYBERSECURITY",
    difficulty: "medium",
  },
  {
    code: "TRUMAN-SHOW",
    name: "Le film dans un film",
    hint: "Jim Carrey. Sa vie entière est spectacle.",
    location: "Devinette — la réponse est le code",
    points: 15,
    category: "MOVIES",
    difficulty: "medium",
  },
  {
    code: "TURING-TEST",
    name: "Robot de test Turing",
    hint: "Intelligence artificielle conversationnelle.",
    location: "Devinette — la réponse est le code",
    points: 25,
    category: "AI",
    difficulty: "hard",
  },
  {
    code: "VALORANT-PRO",
    name: "Streameur valorant pro",
    hint: "Riot Games. Tir tactique 5v5.",
    location: "Devinette — la réponse est le code",
    points: 15,
    category: "GAMING",
    difficulty: "medium",
  },
  {
    code: "VAN-GOGH",
    name: "Peintre oreille coupée",
    hint: "Nuit étoilée. Folie. Génie.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "ART-HISTORY",
    difficulty: "easy",
  },
  {
    code: "VIM-EDITOR",
    name: "Éditeur texte terminal vim",
    hint: "Quitter: :q! Impossible de sortir.",
    location: "Devinette — la réponse est le code",
    points: 25,
    category: "PROGRAMMING",
    difficulty: "hard",
  },
  {
    code: "VPN-ENCRYPTION",
    name: "VPN tunnel chiffré",
    hint: "IP cachée. Trafic sécurisé.",
    location: "Devinette — la réponse est le code",
    points: 20,
    category: "CYBERSECURITY",
    difficulty: "medium",
  },
  {
    code: "WALTER-WHITE",
    name: "Célèbre série Break Bad",
    hint: "Say my name.",
    location: "Devinette — la réponse est le code",
    points: 20,
    category: "TV",
    difficulty: "medium",
  },
  {
    code: "WANNACRY",
    name: "Virus informatique célèbre",
    hint: "2017 ransomware. Cryptage massif.",
    location: "Devinette — la réponse est le code",
    points: 20,
    category: "CYBERSECURITY-HISTORY",
    difficulty: "medium",
  },
  {
    code: "WEBSOCKET-RT",
    name: "Websocket communication temps réel",
    hint: "Bidirectionnel. Connexion persistante.",
    location: "Devinette — la réponse est le code",
    points: 25,
    category: "PROGRAMMING",
    difficulty: "hard",
  },
  {
    code: "WOMAN-CAT-MEME",
    name: "Meme woman pointing cat",
    hint: "Femme crie. Chat confus regarde.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "INTERNET-MEMES",
    difficulty: "easy",
  },
  {
    code: "WONDER-WOMAN",
    name: "Actrice super héros Wonder",
    hint: "Gal Gadot. Amazone. Lasso.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "MOVIES",
    difficulty: "easy",
  },
  {
    code: "YEET-MEME",
    name: "Héros qui dit YEET",
    hint: "Jeune. Tendance. Lancé loin.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "INTERNET-MEMES",
    difficulty: "easy",
  },
  {
    code: "YOUTUBE",
    name: "Plateforme vidéo red",
    hint: "Google. Partage. Monétisation.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "TECH",
    difficulty: "easy",
  },
  {
    code: "ZERO-DAY",
    name: "Zero day exploitation",
    hint: "Faille inconnue. Non patchée.",
    location: "Devinette — la réponse est le code",
    points: 25,
    category: "CYBERSECURITY",
    difficulty: "hard",
  },
  {
    code: "SIN-100-UNLOCK",
    name: "Deuxième palier",
    hint: "100 secrets trouvés. À mi-chemin de la fin. Accordé automatiquement.",
    location: "Palier automatique — 100 secrets trouvés",
    points: 50,
    category: "META",
    difficulty: "medium",
    unlockAt: 100,
  },
  {
    code: "SIN-FINAL-BOSS-ULTIMATE",
    name: "Le grand final",
    hint: "Trouve les 149 autres. Ce dernier vaut 150 points et s'accorde tout seul. Légende absolue.",
    location: "Palier automatique — 149 secrets trouvés",
    points: 150,
    category: "META",
    difficulty: "insane",
    badgeSlug: "legend",
    unlockAt: 149,
  },
  {
    code: "SIN-FIRST-UNLOCK",
    name: "Premier palier",
    hint: "50 secrets trouvés. Accordé automatiquement, en même temps que la légende.",
    location: "Palier automatique — 50 secrets trouvés",
    points: 50,
    category: "META",
    difficulty: "medium",
    unlockAt: 50,
  },
  {
    code: "SIN-LEGENDE",
    name: "La légende",
    hint: "Trouve 50 secrets. Celui-ci s'ouvre tout seul — il ne se tape pas.",
    location: "Palier automatique — 50 secrets trouvés",
    points: 50,
    category: "META",
    difficulty: "insane",
    badgeSlug: "secret",
    unlockAt: 50,
  },
]
