// Secret-hunt codes. Students find or work out a code, redeem it on /chasse,
// and earn points (+ an optional badge). Edit here for the starting set, or
// manage live in the admin console (Secrets tab). The seed upserts on `code`,
// so re-running it corrects anything edited by hand in the admin.
//
// Three kinds of secret live in this list, and `location` says which:
//
//   "Devinette — …"      the hint is a riddle and the code is its answer.
//                        Nothing is hidden anywhere; the student just knows it.
//   "À IMPLÉMENTER — …"  the code is meant to be hidden in the site, and is not
//                        yet. The hint deliberately promises nothing.
//   "Connaissance — …"   the code names a real vulnerability that this site does
//                        NOT have and must never be given. ==Do not "implement"
//                        these== — the point is to recognise the attack, not to
//                        make a school site injectable so a student can score.
//   "Palier automatique" granted by lib/milestones.ts when a student reaches
//                        `unlockAt` non-milestone secrets. Typing it is refused.
//
// `location` is admin-only and is shown to a student only after they find it;
// `hint` is the public clue on the hunt board.

export type SecretDifficulty = "easy" | "medium" | "hard" | "insane"

export interface SecretSeed {
  code: string
  name: string
  hint: string
  location: string
  points: number
  category: string
  difficulty: SecretDifficulty
  badgeSlug?: string
  /**
   * L'endroit du site où ce code est réellement posé, quand il l'est.
   *
   * Le nom d'emplacement vit ici, le code reste en base : une page demande
   * « le secret posé à tel endroit » et n'écrit jamais la réponse dans le
   * dépôt. Les valeurs possibles sont celles de `lib/secret-placements.ts`,
   * et `tests/secret-placements.test.ts` vérifie que chacune est pourvue une
   * fois et une seule.
   */
  placement?: string
  /**
   * Number of NON-milestone secrets a student must have found for this one to
   * be granted automatically. `undefined` for an ordinary secret.
   *
   * The final milestone's value is the count of ordinary secrets, so adding an
   * ordinary secret without bumping it would make the "find everything" reward
   * fire one secret early. tests/secret-seeds.test.ts asserts the two match.
   */
  unlockAt?: number
}

export const SECRET_SEEDS: SecretSeed[] = [
  {
    code: "1984-ORWELL",
    name: "Livre dystopie 1984",
    hint: "Big Brother. Totalitarisme. Dystopie.",
    location: "Devinette — la réponse est le code",
    points: 20,
    category: "BOOKS",
    difficulty: "medium",
  },
  {
    code: "2FA-TOTP",
    name: "Authentification deux facteurs",
    hint: "Google Authenticator. Code temporaire.",
    location: "Devinette — la réponse est le code",
    points: 20,
    category: "CYBERSECURITY",
    difficulty: "medium",
  },
  {
    code: "ACHERON",
    name: "Personnage de la Nihilité du jeu Honkai Star Rail",
    hint: "Honkai, nihilité, elle tue.",
    location: "Devinette — la réponse est le code",
    points: 20,
    category: "GAMING-ANIME",
    difficulty: "medium",
  },
  {
    code: "ALPHAZERO-CHESS",
    name: "Jeu échecs AlphaZero IA",
    hint: "Deep Mind. Self-play. Surhumain.",
    location: "Devinette — la réponse est le code",
    points: 30,
    category: "AI-GAMING",
    difficulty: "hard",
  },
  {
    code: "AMONG-US-SUS",
    name: "Le jeu de l'imposteur dans un vaisseau spatial",
    hint: "Sorti en 2018, ignoré, puis mondial deux ans plus tard pendant le confinement.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "INTERNET-MEMES",
    difficulty: "easy",
  },
  {
    code: "ANONYMOUS",
    name: "Hackers légendaires",
    hint: "Guy Fawkes masks. Hacktivist.",
    location: "Devinette — la réponse est le code",
    points: 20,
    category: "HACKING-HISTORY",
    difficulty: "medium",
  },
  {
    code: "ASTEROID-DINO",
    name: "Astéroïde dans l'espace",
    hint: "K-T extinction. Dinosaures disparus.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "SCIENCE",
    difficulty: "easy",
  },
  {
    code: "ATTACK-ON-TITAN",
    name: "Anime avec des titans",
    hint: "Shingeki no Kyojin.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "ANIME",
    difficulty: "easy",
  },
  {
    code: "AVENGERS-RUSSO",
    name: "Les deux frères qui ont réalisé Endgame",
    hint: "Ils viennent de la comédie télévisée et ont signé quatre films Marvel, dont le plus gros succès de la saga.",
    location: "Devinette — la réponse est le code",
    points: 20,
    category: "MOVIES",
    difficulty: "medium",
  },
  {
    code: "BANE",
    name: "The Dark Knight Rises : le vilain",
    hint: "You merely adopted the dark.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "MOVIES",
    difficulty: "easy",
  },
  {
    code: "BATMAN-ARKHAM",
    name: "La série de jeux où l'on est la chauve-souris de Gotham",
    hint: "Un asile puis une ville : on plane, on interroge, et on frappe en rythme.",
    location: "Devinette — la réponse est le code",
    points: 20,
    category: "GAMING",
    difficulty: "medium",
  },
  {
    code: "BEETHOVEN",
    name: "Compositeur sourd génial",
    hint: "9e symphonie. Symphonie inaudible.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "MUSIC-HISTORY",
    difficulty: "easy",
  },
  {
    code: "BILLIE-EILISH",
    name: "Musicienne pop blonde",
    hint: "Bad guy. Jeune. Whisper vocal.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "MUSIC",
    difficulty: "easy",
  },
  {
    code: "BLACK-HOLE",
    name: "Trou noir gravité limite",
    hint: "Event horizon. Singularité.",
    location: "Devinette — la réponse est le code",
    points: 20,
    category: "ASTRONOMY",
    difficulty: "medium",
  },
  {
    code: "BLOCKCHAIN-POW",
    name: "Concept blockchain mining",
    hint: "Preuve de travail. Mineur.",
    location: "Devinette — la réponse est le code",
    points: 30,
    category: "TECH",
    difficulty: "hard",
  },
  {
    code: "BRAVE-NEW-WORLD",
    name: "La dystopie où l'on est soumis par le plaisir, pas par la peur",
    hint: "Huxley imagine des humains fabriqués en série et une drogue qui rend la révolte inutile.",
    location: "Devinette — la réponse est le code",
    points: 20,
    category: "BOOKS",
    difficulty: "medium",
  },
  {
    code: "C64-PROGRAMMER",
    name: "Programmeur du Commodore 64",
    hint: "Atari, premiers jeux, 8-bit.",
    location: "Devinette — la réponse est le code",
    points: 20,
    category: "TECH-HISTORY",
    difficulty: "medium",
  },
  {
    code: "CHICKEN-JOKE",
    name: "Pourquoi la poule traverse la route",
    hint: "Blague classique. De l'autre côté.",
    location: "Devinette — la réponse est le code",
    points: 8,
    category: "JOKES",
    difficulty: "easy",
  },
  {
    code: "CICD-PIPELINE",
    name: "CI/CD pipeline automation",
    hint: "Jenkins. GitLab. Automatisation.",
    location: "Devinette — la réponse est le code",
    points: 30,
    category: "DEVOPS",
    difficulty: "hard",
  },
  {
    code: "CIVILIZATION",
    name: "Jeu de stratégie au tour par tour",
    hint: "Sid Meier. Construction empire.",
    location: "Devinette — la réponse est le code",
    points: 20,
    category: "GAMING",
    difficulty: "medium",
  },
  {
    code: "CRYPTOLOCKER",
    name: "Le rançongiciel de 2013 qui a lancé la mode",
    hint: "Le premier à réclamer un paiement en bitcoin contre la clé de déchiffrement ; des milliers de victimes ont payé.",
    location: "Devinette — la réponse est le code",
    points: 30,
    category: "CYBERSECURITY",
    difficulty: "hard",
  },
  {
    code: "DDOS-FLOOD",
    name: "DDoS attack flooding",
    hint: "Déni de service. Saturation serveur.",
    location: "Devinette — la réponse est le code",
    points: 30,
    category: "CYBERSECURITY",
    difficulty: "hard",
  },
  {
    code: "DEATH-NOTE",
    name: "Le cahier qui tue celui dont on y écrit le nom",
    hint: "Un lycéen le ramasse et se prend pour un dieu ; un détective sans visage le traque.",
    location: "Devinette — la réponse est le code",
    points: 20,
    category: "ANIME",
    difficulty: "medium",
  },
  {
    code: "DESTINY2",
    name: "Eyes Up Guardian",
    hint: "Un jeu de tir sci-fi avec des Gardiens.",
    location: "Devinette — la réponse est le code",
    points: 30,
    category: "GAMING",
    difficulty: "hard",
  },
  {
    code: "DICAPRIO",
    name: "L'acteur qui a attendu vingt-cinq ans son premier Oscar",
    hint: "Titanic, des rêves imbriqués, un ours — et une statuette enfin obtenue en 2016.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "MOVIES",
    difficulty: "easy",
  },
  {
    code: "DIGITAL-RAIN",
    name: "The Matrix code rain",
    hint: "Caractères verts tombant. Iconic.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "MOVIES-AESTHETIC",
    difficulty: "easy",
  },
  {
    code: "DISTRACTED-BF",
    name: "Meme distracted boyfriend",
    hint: "Garçon regarde autre fille.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "INTERNET-MEMES",
    difficulty: "easy",
  },
  {
    code: "DOCKER",
    name: "Le conteneur qui a tué « ça marche sur ma machine »",
    hint: "Il emporte l'application et tout ce dont elle dépend, pour que la même chose tourne partout.",
    location: "Devinette — la réponse est le code",
    points: 20,
    category: "DEVOPS",
    difficulty: "medium",
  },
  {
    code: "DOGE-SHIBE",
    name: "Meme du Doge",
    hint: "Much wow. Very meme. So internet.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "INTERNET-MEMES",
    difficulty: "easy",
  },
  {
    code: "DRAKE-MEME",
    name: "Meme Drake réaction",
    hint: "Pas bien. Très bien. Haut bas.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "INTERNET-MEMES",
    difficulty: "easy",
  },
  {
    code: "DUNE-FRANK",
    name: "Roman science-fiction Dune",
    hint: "Épices. Désert. Politiques.",
    location: "Devinette — la réponse est le code",
    points: 20,
    category: "BOOKS",
    difficulty: "medium",
  },
  {
    code: "E-MC2",
    name: "Équation célèbre Einstein",
    hint: "Énergie = Masse × Vitesse².",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "SCIENCE",
    difficulty: "easy",
  },
  {
    code: "EIICHIRO-ODA",
    name: "Mangaka d'One Piece",
    hint: "Pirate, trésor, aventure infinie.",
    location: "Devinette — la réponse est le code",
    points: 20,
    category: "MANGA-CREATORS",
    difficulty: "medium",
  },
  {
    code: "EINSTEIN",
    name: "Scientifique avec cheveux fous",
    hint: "E=mc². Génie foufou.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "HISTORY",
    difficulty: "easy",
  },
  {
    code: "ELDEN-RING",
    name: "Le monde ouvert de FromSoftware écrit avec l'auteur du Trône de fer",
    hint: "Aucune flèche ne te guide : tu meurs, tu comprends, tu recommences.",
    location: "Devinette — la réponse est le code",
    points: 20,
    category: "GAMING",
    difficulty: "medium",
  },
  {
    code: "ELSA",
    name: "La reine des neiges",
    hint: "Let it go. Libérée, délivrée.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "MOVIES",
    difficulty: "easy",
  },
  {
    code: "EMINEM",
    name: "Le rappeur de Détroit au débit le plus rapide",
    hint: "Un alter ego nommé Slim Shady, et un film où il joue à peu près son propre rôle.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "MUSIC",
    difficulty: "easy",
  },
  {
    code: "ETHEREUM-SMART",
    name: "Cryptocurrency Ethereum",
    hint: "Vitalik Buterin. Contrats intelligents.",
    location: "Devinette — la réponse est le code",
    points: 20,
    category: "TECH",
    difficulty: "medium",
  },
  {
    code: "FACEBOOK",
    name: "Réseau social face",
    hint: "Meta. Zuckerberg. Données.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "TECH",
    difficulty: "easy",
  },
  {
    code: "FAUST",
    name: "L'homme qui vend son âme contre la connaissance",
    hint: "Légende allemande reprise par Goethe : le diable s'appelle Méphistophélès, et le marché se paye.",
    location: "Devinette — la réponse est le code",
    points: 20,
    category: "LITERATURE",
    difficulty: "medium",
  },
  {
    code: "FIREWALL-RULES",
    name: "Firewall pare-feu réseau",
    hint: "Pare-feu. Ports. Règles trafic.",
    location: "Devinette — la réponse est le code",
    points: 20,
    category: "CYBERSECURITY",
    difficulty: "medium",
  },
  {
    code: "FORTNITE",
    name: "Le battle royale à la troisième personne",
    hint: "On voit son personnage de dos, on construit ses murs, et chaque saison efface la précédente.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "GAMING",
    difficulty: "easy",
  },
  {
    code: "FORTNITE-BATTLE-PASS",
    name: "Battle royale île tempête",
    hint: "100 joueurs. Skin cosmétique.",
    location: "Devinette — la réponse est le code",
    points: 20,
    category: "GAMING",
    difficulty: "medium",
  },
  {
    code: "FRIENDS-TV",
    name: "Série Friends café central",
    hint: "Six amis. New York. Phoebe.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "TV",
    difficulty: "easy",
  },
  {
    code: "GAME-OF-THRONES",
    name: "La série où l'hiver vient depuis huit saisons",
    hint: "Adaptée de romans inachevés, elle a fini par dépasser son auteur — et beaucoup lui en veulent encore.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "TV",
    difficulty: "easy",
  },
  {
    code: "GIGACHAD",
    name: "Meme Giga Chad sigma male",
    hint: "Mentonat. Énorme. Basé.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "INTERNET-MEMES",
    difficulty: "easy",
  },
  {
    code: "GODADDY-HACK",
    name: "Passe-partout GoDaddy",
    hint: "2021 breach. Registrar compromis.",
    location: "Devinette — la réponse est le code",
    points: 30,
    category: "CYBERSECURITY-HISTORY",
    difficulty: "hard",
  },
  {
    code: "GOKU",
    name: "Le personnage qui sauve l'univers Dragon Ball",
    hint: "Kamehameha !",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "ANIME",
    difficulty: "easy",
  },
  {
    code: "GOOGLE-SEARCH",
    name: "Moteur recherche spider",
    hint: "Web crawler. PageRank. Publicité.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "TECH",
    difficulty: "easy",
  },
  {
    code: "GPL-LICENSE",
    name: "GPL copyleft obligation",
    hint: "Source accessible. Dérivés libres.",
    location: "Devinette — la réponse est le code",
    points: 20,
    category: "TECH",
    difficulty: "medium",
  },
  {
    code: "GRAPHQL-QUERY",
    name: "GraphQL requête flexible",
    hint: "Facebook. Requête données précises.",
    location: "Devinette — la réponse est le code",
    points: 20,
    category: "PROGRAMMING",
    difficulty: "medium",
  },
  {
    code: "GRUMPY-CAT",
    name: "La chatte dont le visage furieux venait d'un défaut de mâchoire",
    hint: "Elle n'était pas de mauvaise humeur : c'était du nanisme félin. Elle a rapporté des millions.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "INTERNET-MEMES",
    difficulty: "easy",
  },
  {
    code: "HARRY-POTTER",
    name: "L'orphelin à cicatrice envoyé dans une école de sorciers",
    hint: "Sept livres, une gare imaginaire au quai 9¾, et un nom que personne n'ose prononcer.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "BOOKS",
    difficulty: "easy",
  },
  {
    code: "HIGGS-BOSON",
    name: "Particule élémentaire boson",
    hint: "Masse. CERN. Dieu particulaire.",
    location: "Devinette — la réponse est le code",
    points: 30,
    category: "PHYSICS",
    difficulty: "hard",
  },
  {
    code: "HIMYM",
    name: "Sitcom How I Met Mother",
    hint: "Ted Mosby. Mère. Fin controversée.",
    location: "Devinette — la réponse est le code",
    points: 20,
    category: "TV",
    difficulty: "medium",
  },
  {
    code: "HOLLOW-KNIGHT",
    name: "Le jeu 2D dans un royaume d'insectes en ruine",
    hint: "Dessiné à la main, difficile, silencieux : le héros ne parle jamais et la carte ne se donne pas.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "GAMING",
    difficulty: "easy",
  },
  {
    code: "HTTPS-SSL",
    name: "Protocole sécurité HTTPS",
    hint: "Certificat. Chiffrement. Cadenas.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "CYBERSECURITY",
    difficulty: "easy",
  },
  {
    code: "IDRIS",
    name: "Mot de passe oublié",
    hint: "Je suis le premier à avoir oublié mon mot de passe.",
    location: "Devinette — la réponse est le code",
    points: 20,
    category: "SECURITY",
    difficulty: "medium",
  },
  {
    code: "INCEPTION",
    name: "Le film où l'on entre dans le rêve d'un rêve",
    hint: "Chaque niveau ralentit le temps, et une toupie décide si l'on est encore dedans.",
    location: "Devinette — la réponse est le code",
    points: 30,
    category: "MOVIES",
    difficulty: "hard",
  },
  {
    code: "IRONMAN",
    name: "L'industriel dans une armure rouge et or",
    hint: "Milliardaire et ingénieur, il construit sa première armure dans une grotte avec une caisse de ferraille.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "COMICS-MOVIES",
    difficulty: "easy",
  },
  {
    code: "KEVIN-MITNICK",
    name: "Hacker célèbre lunettes",
    hint: "Phone hacker. Social engineering.",
    location: "Devinette — la réponse est le code",
    points: 20,
    category: "HACKING-HISTORY",
    difficulty: "medium",
  },
  {
    code: "KUBERNETES",
    name: "Le chef d'orchestre des conteneurs",
    hint: "Il redémarre ce qui tombe et duplique ce qui sature sans qu'on le lui demande. Son surnom cache huit lettres entre un K et un s.",
    location: "Devinette — la réponse est le code",
    points: 30,
    category: "DEVOPS",
    difficulty: "hard",
  },
  {
    code: "LINK",
    name: "Le héros de Zelda",
    hint: "Verte tunique. Ne parle jamais.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "GAMING",
    difficulty: "easy",
  },
  {
    code: "LINUX",
    name: "Le noyau au manchot",
    hint: "Ce n'est pas un système complet mais la pièce centrale : les distributions se construisent autour de lui. Sa mascotte est un manchot, pas un pingouin.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "TECH",
    difficulty: "easy",
  },
  {
    code: "LOSS-MEME",
    name: "Meme Loss référence",
    hint: "Quatre bandes. Trois debout. Un couché.",
    location: "Devinette — la réponse est le code",
    points: 30,
    category: "INTERNET-MEMES",
    difficulty: "hard",
  },
  {
    code: "MATRIX",
    name: "Le film où le monde réel est une simulation",
    hint: "Pilule rouge ou bleue, balles esquivées au ralenti, et une pluie de caractères verts.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "MOVIES",
    difficulty: "easy",
  },
  {
    code: "MICROSERVICES",
    name: "L'architecture qui découpe l'application en petits services",
    hint: "Chacun se déploie seul et peut tomber seul — ce qui règle un problème et en crée dix autres.",
    location: "Devinette — la réponse est le code",
    points: 30,
    category: "DEVOPS",
    difficulty: "hard",
  },
  {
    code: "MIT-LICENSE",
    name: "Licence logiciel MIT libre",
    hint: "Très permissif. Gratuit. Code ouvert.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "TECH",
    difficulty: "easy",
  },
  {
    code: "MITM-ATTACK",
    name: "Man-in-the-middle attack",
    hint: "Interception réseau. Écoute active.",
    location: "Devinette — la réponse est le code",
    points: 30,
    category: "CYBERSECURITY",
    difficulty: "hard",
  },
  {
    code: "MONGODB",
    name: "Base de données NoSQL",
    hint: "JSON, flexible, scalable.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "PROGRAMMING",
    difficulty: "easy",
  },
  {
    code: "MOSAIC-NETSCAPE",
    name: "Le navigateur qui a rendu le web grand public",
    hint: "Il n'était pas le premier — celui de Tim Berners-Lee l'a précédé de trois ans — mais c'est lui qui, en 1993, a mis des images à côté du texte et fait sortir le web des laboratoires.",
    location: "Devinette — la réponse est le code",
    points: 20,
    category: "WEB-HISTORY",
    difficulty: "medium",
  },
  {
    code: "NARUTO",
    name: "Manga de ninjas",
    hint: "Shinobi, chakra, amitié.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "ANIME-MANGA",
    difficulty: "easy",
  },
  {
    code: "NEURAL-NETWORKS",
    name: "Le modèle inspiré des neurones du cerveau",
    hint: "Des couches de petites unités qui s'ajustent à chaque erreur : c'est la brique de tout l'apprentissage profond.",
    location: "Devinette — la réponse est le code",
    points: 30,
    category: "AI",
    difficulty: "hard",
  },
  {
    code: "NEVER-GONNA-GIVE",
    name: "Chanson Rickroll URL",
    hint: "1987 hit. Rick Astley.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "INTERNET-CULTURE",
    difficulty: "easy",
  },
  {
    code: "NICE-NUMBER",
    name: "Number 69 nice",
    hint: "Nice.",
    location: "Devinette — la réponse est le code",
    points: 69,
    category: "INTERNET-MEMES",
    difficulty: "easy",
  },
  {
    code: "NIGHTCORE",
    name: "Type de musique speedrun",
    hint: "Chanson accélérée avec voix aiguë. C'est un meme.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "MUSIC",
    difficulty: "easy",
  },
  {
    code: "NLP-TRANSFORMERS",
    name: "NLP natural language processing",
    hint: "BERT. GPT. Langage naturel.",
    location: "Devinette — la réponse est le code",
    points: 30,
    category: "AI",
    difficulty: "hard",
  },
  {
    code: "NOTCH-MINECRAFT",
    name: "Le Createur de Minecraft",
    hint: "Blocs. Infini. Créativité sandbox.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "GAMING-CREATORS",
    difficulty: "easy",
  },
  {
    code: "ONE-RING",
    name: "L'arme de destruction du Seigneur des Anneaux",
    hint: "Un anneau pour les gouverner tous.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "MOVIES-BOOKS",
    difficulty: "easy",
  },
  {
    code: "OWASP-INJECTION",
    name: "OWASP Top 10 injection",
    hint: "Injection SQL, NoSQL, LDAP.",
    location: "Devinette — la réponse est le code",
    points: 30,
    category: "CYBERSECURITY",
    difficulty: "hard",
  },
  {
    code: "PEWDIEPIE",
    name: "Youtuber gaming furieux",
    hint: "Felix. Suédois. Minecraft gaming.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "YOUTUBERS",
    difficulty: "easy",
  },
  {
    code: "PHISHING-SCAM",
    name: "Phishing mail faux",
    hint: "Email imposteur. Vol credentials.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "CYBERSECURITY",
    difficulty: "easy",
  },
  {
    code: "PLATO-CAVE",
    name: "Philosophe cave allégorie",
    hint: "Ombres. Réalité. Illusion.",
    location: "Devinette — la réponse est le code",
    points: 30,
    category: "PHILOSOPHY",
    difficulty: "hard",
  },
  {
    code: "POKIMANE",
    name: "Streamer esport extrême",
    hint: "League of Legends. Twitch reine.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "STREAMERS",
    difficulty: "easy",
  },
  {
    code: "PYTHON",
    name: "Le langage nommé d'après une troupe comique",
    hint: "Guido van Rossum lisait les sketchs des Monty Python en l'écrivant — le serpent est venu après, sur le logo.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "PROGRAMMING",
    difficulty: "easy",
  },
  {
    code: "RAGE-FACE",
    name: "Le gros meme 2010",
    hint: "FUUUUU—————",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "INTERNET-MEMES",
    difficulty: "easy",
  },
  {
    code: "REACT",
    name: "La bibliothèque qui a imposé les composants",
    hint: "Ce n'est pas un framework et sa documentation insiste là-dessus : elle ne fait qu'une chose, l'interface, et te laisse choisir le reste. Née chez Facebook.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "PROGRAMMING",
    difficulty: "easy",
  },
  {
    code: "RECAPTCHA",
    name: "CAPTCHA robot verification",
    hint: "Je ne suis pas un robot.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "SECURITY",
    difficulty: "easy",
  },
  {
    code: "REST-API",
    name: "Le style d'architecture qui a rangé le web",
    hint: "Ce n'est pas un protocole : c'est une façon d'utiliser HTTP où chaque chose a une adresse, et où le verbe employé dit ce qu'on en fait.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "PROGRAMMING",
    difficulty: "easy",
  },
  {
    code: "RICKROLL",
    name: "La chanson de 1987 qui piège encore les liens",
    hint: "Tu cliques sur autre chose, et c'est elle qui démarre.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "INTERNET-MEMES",
    difficulty: "easy",
  },
  {
    code: "RUBIKS-ANIME",
    name: "Anime cubes colorés",
    hint: "Cubes de Rubik années 90.",
    location: "Devinette — la réponse est le code",
    points: 20,
    category: "ANIME",
    difficulty: "medium",
  },
  {
    code: "SATOSHI-NAKAMOTO",
    name: "Créateur de Bitcoin",
    hint: "Crypto, blockchain, mystérieux.",
    location: "Devinette — la réponse est le code",
    points: 30,
    category: "TECH",
    difficulty: "hard",
  },
  {
    code: "SCP-FOUNDATION",
    name: "Mystère SCP containment",
    hint: "Objets surnaturels. Confinement secret.",
    location: "Devinette — la réponse est le code",
    points: 20,
    category: "INTERNET-HORROR",
    difficulty: "medium",
  },
  {
    code: "SHERLOCK",
    name: "Le détective du 221B Baker Street",
    hint: "Il déduit d'une trace de boue d'où tu viens — et son auteur a essayé de le tuer pour s'en débarrasser.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "BOOKS-TV",
    difficulty: "easy",
  },
  {
    code: "SIN-404",
    name: "Perdu mais pas pour tout le monde",
    hint: "Que se passe-t-il si tu demandes une page qui n'existe pas ?",
    location: "Page 404 personnalisée",
    points: 10,
    category: "WEB",
    difficulty: "easy",
  },
  {
    code: "SIN-ADMIN",
    name: "La page secrète /admin",
    hint: "Certains chemins d'URL sont tellement prévisibles qu'on les essaie en premier.",
    location: "Dans le code de la page /admin",
    points: 30,
    category: "WEB",
    difficulty: "hard",
    placement: "admin-path",
  },
  {
    code: "SIN-API-KEY-HARDCODED",
    name: "API key en dur",
    hint: "Une clé d'API écrite en dur dans le code d'une page est lisible par tout le monde. C'est une des fautes les plus courantes.",
    location: "Fausse clé dans la configuration client de /cyber",
    points: 30,
    category: "CYBERSECURITY",
    difficulty: "hard",
    placement: "api-key",
  },
  {
    code: "SIN-BACKUP-FILE",
    name: "Backup .bak oublié",
    hint: "Un fichier de sauvegarde oublié à côté de l'original garde en général tout son contenu.",
    location: "/backup.bak, à la racine du site",
    points: 50,
    category: "CYBERSECURITY",
    difficulty: "insane",
    placement: "backup-file",
  },
  {
    code: "SIN-BASE64-DECODE",
    name: "Décode-moi Base64",
    hint: "Le Base64 n'est pas du chiffrement, seulement un encodage. N'importe quel décodeur en ligne suffit à le lire.",
    location: "Chaîne encodée en Base64 sur /cyber",
    points: 20,
    category: "ENCODING",
    difficulty: "medium",
    placement: "base64",
  },
  {
    code: "SIN-CONSOLE",
    name: "Message dans la console",
    hint: "Les navigateurs ont une console pour les développeurs. Ouvre-la (F12) et lis bien.",
    location: "console.log au chargement du site",
    points: 10,
    category: "WEB",
    difficulty: "easy",
  },
  {
    code: "SIN-CSS-DISPLAY-NONE",
    name: "Cache-cache CSS display none",
    hint: "Le CSS sait rendre un texte invisible sans le supprimer. Sélectionne toute la page pour t'en convaincre.",
    location: "Texte masqué en CSS sur /chasse — il ressort en sélectionnant la page",
    points: 30,
    category: "WEB",
    difficulty: "hard",
    placement: "hidden-css",
  },
  {
    code: "SIN-DEBUG-PARAM",
    name: "Paramètre debug true secret",
    hint: "Un paramètre d'URL oublié en production peut en dire beaucoup trop.",
    location: "Page /vie (jeu de la vie) — panneau de debug affiché par ?debug=true",
    points: 30,
    category: "WEB",
    difficulty: "hard",
  },
  {
    code: "SIN-DOCKER-ENV",
    name: "Configuration Docker exposée",
    hint: "Le fichier qui porte les variables d'environnement d'un conteneur, mots de passe compris. Il ne doit jamais être servi par le web.",
    location: "Connaissance — la faille n'existe pas ici et ne doit jamais être créée",
    points: 30,
    category: "CYBERSECURITY",
    difficulty: "hard",
  },
  {
    code: "SIN-GIT-EXPOSED",
    name: "Dossier Git exposé",
    hint: "Quand un serveur laisse traîner son dossier de versionnement à la racine, tout l'historique du code devient public. Ce site ne le fait pas — beaucoup le font.",
    location: "Connaissance — la faille n'existe pas ici et ne doit jamais être créée",
    points: 50,
    category: "CYBERSECURITY",
    difficulty: "insane",
  },
  {
    code: "SIN-HEADER-CUSTOM",
    name: "Headers HTTP secrets",
    hint: "Une réponse HTTP ne contient pas que la page : elle transporte aussi des en-têtes que le navigateur ne montre pas.",
    location: "En-tête X-Custom-Secret de la réponse /api/decoy",
    points: 30,
    category: "CYBERSECURITY",
    difficulty: "hard",
    placement: "header",
  },
  {
    code: "SIN-JWT-DECODE",
    name: "JWT token decodé",
    hint: "Un JWT n'est pas chiffré : sa charge utile est du Base64 que n'importe qui peut lire. La signature protège l'intégrité, pas le secret.",
    location: "Charge utile d'un JWT de démonstration sur /cyber",
    points: 30,
    category: "CYBERSECURITY",
    difficulty: "hard",
    placement: "jwt",
  },
  {
    code: "SIN-KONAMI",
    name: "Le code Konami",
    hint: "Les vieux joueurs connaissent la combinaison magique. Essaie-la sur la page d'accueil.",
    location: "Accueil : séquence clavier ↑ ↑ ↓ ↓ ← → ← → B A",
    points: 30,
    category: "EASTER-EGG",
    difficulty: "hard",
    badgeSlug: "secret",
  },
  {
    code: "SIN-LOCALSTORAGE-HACK",
    name: "LocalStorage infiltration admin",
    hint: "Le navigateur garde des données pour chaque site. Outils de développement, onglet Application, Local Storage.",
    location: "Clé leurre écrite dans le localStorage par /chasse",
    points: 20,
    category: "WEB",
    difficulty: "medium",
    placement: "local-storage",
  },
  {
    code: "SIN-NETWORK-SPY",
    name: "Requête réseau suspecte",
    hint: "L'onglet Réseau des outils de développement montre tout ce qu'une page demande vraiment, pas seulement ce qu'elle affiche.",
    location: "Réponse de /api/decoy, visible dans l'onglet Réseau depuis /chasse",
    points: 30,
    category: "CYBERSECURITY",
    difficulty: "hard",
    placement: "network",
  },
  {
    code: "SIN-PATH-TRAVERSAL",
    name: "Chemin traversal passwd",
    hint: "Remonter l'arborescence à coups de points-points jusqu'à un fichier qu'on ne devrait pas pouvoir lire. Ne l'essaie pas ici.",
    location: "Connaissance — la faille n'existe pas ici et ne doit jamais être créée",
    points: 50,
    category: "CYBERSECURITY",
    difficulty: "insane",
  },
  {
    code: "SIN-PROF",
    name: "La page secrète",
    hint: "Il paraît qu'une page cachée existe. Son adresse ressemble à un mot que les espions adorent.",
    location: "/secret",
    points: 20,
    category: "WEB",
    difficulty: "medium",
    badgeSlug: "secret",
  },
  {
    code: "SIN-ROBOTS",
    name: "Robots autorisés",
    hint: "Un fichier standard indique aux moteurs de recherche où ne pas aller. Va y jeter un œil.",
    location: "/robots.txt (commentaire)",
    points: 10,
    category: "CYBERSECURITY",
    difficulty: "easy",
  },
  {
    code: "SIN-SERVICE-WORKER-EVIL",
    name: "Service Worker malveillant",
    hint: "Un script qui s'installe dans le navigateur et sert le contenu à la place du serveur. Précieux pour le hors-ligne, redoutable s'il est détourné.",
    location: "Connaissance — la faille n'existe pas ici et ne doit jamais être créée",
    points: 50,
    category: "CYBERSECURITY",
    difficulty: "insane",
  },
  {
    code: "SIN-SOURCE",
    name: "Vue sur la source",
    hint: "Les développeurs regardent toujours sous le capot. Que cache le code d'une page ?",
    location: "Commentaire HTML caché dans le <head> du site",
    points: 10,
    category: "WEB",
    difficulty: "easy",
    badgeSlug: "secret",
  },
  {
    code: "SIN-SQL-INJECT",
    name: "Hack SQL injection",
    hint: "Glisser une apostrophe dans un formulaire pour que la base lise du code là où elle attendait une donnée. La parade tient en deux mots : requêtes paramétrées. Ne l'essaie pas ici.",
    location: "Connaissance — la faille n'existe pas ici et ne doit jamais être créée",
    points: 50,
    category: "CYBERSECURITY",
    difficulty: "insane",
  },
  {
    code: "SIN-SSH-KEY",
    name: "Clé privée SSH exposée",
    hint: "La moitié privée d'une paire de clés ne quitte jamais ta machine. Si elle finit dans un dépôt, elle est brûlée : on la remplace, on ne la cache pas.",
    location: "Connaissance — aucune vraie clé n'existe sur ce site",
    points: 50,
    category: "CYBERSECURITY",
    difficulty: "insane",
  },
  {
    code: "SIN-TERMINAL",
    name: "L'invité du terminal",
    hint: "Dans le terminal, une commande peu connue révèle un message. Tape « secret ».",
    location: "Terminal : commande `secret`",
    points: 30,
    category: "HACKING",
    difficulty: "hard",
  },
  {
    code: "SIN-TIMING-TRAP",
    name: "Timing parfait minuit",
    hint: "Certaines choses ne se montrent qu'à une heure très précise.",
    location: "Affiché sur /chasse entre 00h00 et 00h05",
    points: 50,
    category: "HACKING",
    difficulty: "insane",
    placement: "timing",
  },
  {
    code: "SIN-WEAK-PASSWORD",
    name: "Password123 réutilisé",
    hint: "Le couple identifiant/mot de passe qu'un attaquant essaie en tout premier, parce qu'il fonctionne encore beaucoup trop souvent.",
    location: "Connaissance — aucun compte faible ici",
    points: 20,
    category: "CYBERSECURITY",
    difficulty: "medium",
  },
  {
    code: "SIN-ZERO-WIDTH",
    name: "Caractères invisibles Unicode",
    hint: "Unicode contient des caractères de largeur nulle : invisibles à l'œil, bien présents au copier-coller.",
    location: "Caractères de largeur nulle dans un paragraphe de /docs",
    points: 30,
    category: "ENCODING",
    difficulty: "hard",
    placement: "zero-width",
  },
  {
    code: "SLENDERMAN",
    name: "L'homme sans visage né sur un forum en 2009",
    hint: "Créature inventée pour un concours de photos truquées, devenue légende — puis un fait divers bien réel.",
    location: "Devinette — la réponse est le code",
    points: 30,
    category: "INTERNET-HORROR",
    difficulty: "hard",
  },
  {
    code: "SMARTCONTRACT",
    name: "Smart contract Ethereum",
    hint: "Code auto-exécutable blockchain.",
    location: "Devinette — la réponse est le code",
    points: 30,
    category: "TECH",
    difficulty: "hard",
  },
  {
    code: "SPEC-OPS-LINE",
    name: "WAS IT WORTH IT",
    hint: "Spec Ops: The Line. Noir et déprimant.",
    location: "Devinette — la réponse est le code",
    points: 30,
    category: "GAMING",
    difficulty: "hard",
  },
  {
    code: "SPIDERMAN-MEME",
    name: "Meme Spider-man pointer",
    hint: "Deux Spider-mans pointent.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "INTERNET-MEMES",
    difficulty: "easy",
  },
  {
    code: "SPONGEBOB-GAME",
    name: "Platformer avec éponge",
    hint: "Bikini Bottom. Perle. Jeu PS1.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "GAMING",
    difficulty: "easy",
  },
  {
    code: "SQUEEZIE",
    name: "Youtubeur gaming français",
    hint: "CyRide, Minecraft, viral.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "YOUTUBERS",
    difficulty: "easy",
  },
  {
    code: "SQUID-GAME",
    name: "La série coréenne où des jeux d'enfants tuent",
    hint: "456 joueurs endettés, un « un, deux, trois, soleil » qui tourne mal, et une combinaison verte devenue costume d'Halloween.",
    location: "Devinette — la réponse est le code",
    points: 20,
    category: "TV",
    difficulty: "medium",
  },
  {
    code: "SSH-PROTOCOL",
    name: "Protocole SSH sécurité",
    hint: "Port 22. Remote secure shell.",
    location: "Devinette — la réponse est le code",
    points: 20,
    category: "CYBERSECURITY",
    difficulty: "medium",
  },
  {
    code: "STEVE-JOBS",
    name: "Fondateur Apple fruité",
    hint: "Pomme croquée. Design. Minimalisme.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "TECH-PEOPLE",
    difficulty: "easy",
  },
  {
    code: "SUPERMAN",
    name: "Héros DC alien bleu",
    hint: "Krypton. Cape rouge. Invulnérable.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "COMICS",
    difficulty: "easy",
  },
  {
    code: "TARANTINO",
    name: "Le réalisateur qui raconte ses films dans le désordre",
    hint: "Dialogues interminables, violence stylisée, et une obsession pour les pieds dont il ne se cache pas.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "MOVIES",
    difficulty: "easy",
  },
  {
    code: "TERRAFORM-IAC",
    name: "Infrastructure as Code IaC",
    hint: "Terraform. Infra codée.",
    location: "Devinette — la réponse est le code",
    points: 20,
    category: "DEVOPS",
    difficulty: "medium",
  },
  {
    code: "THANOS-INFINITY",
    name: "Le plan de Thanos",
    hint: "Avec un clic. Mais à quel prix ?",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "MOVIES",
    difficulty: "easy",
  },
  {
    code: "THEOFFICE",
    name: "Série The Office mockumentary",
    hint: "Bureau. Humour gêne. Mockumentaire.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "TV",
    difficulty: "easy",
  },
  {
    code: "TROJAN-MALWARE",
    name: "Malware Trojan horse",
    hint: "Cheval Troie. Infecte discrètement.",
    location: "Devinette — la réponse est le code",
    points: 20,
    category: "CYBERSECURITY",
    difficulty: "medium",
  },
  {
    code: "TRUMAN-SHOW",
    name: "Le film dans un film",
    hint: "Jim Carrey. Sa vie entière est spectacle.",
    location: "Devinette — la réponse est le code",
    points: 20,
    category: "MOVIES",
    difficulty: "medium",
  },
  {
    code: "TURING-TEST",
    name: "Robot de test Turing",
    hint: "Intelligence artificielle conversationnelle.",
    location: "Devinette — la réponse est le code",
    points: 30,
    category: "AI",
    difficulty: "hard",
  },
  {
    code: "VALORANT-PRO",
    name: "Le tir tactique 5 contre 5 de Riot Games",
    hint: "Des agents à pouvoirs sur des cartes où une balle dans la tête suffit.",
    location: "Devinette — la réponse est le code",
    points: 20,
    category: "GAMING",
    difficulty: "medium",
  },
  {
    code: "VAN-GOGH",
    name: "Peintre oreille coupée",
    hint: "Nuit étoilée. Folie. Génie.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "ART-HISTORY",
    difficulty: "easy",
  },
  {
    code: "VIM-EDITOR",
    name: "Éditeur texte terminal vim",
    hint: "Quitter: :q! Impossible de sortir.",
    location: "Devinette — la réponse est le code",
    points: 30,
    category: "PROGRAMMING",
    difficulty: "hard",
  },
  {
    code: "VPN-ENCRYPTION",
    name: "VPN tunnel chiffré",
    hint: "IP cachée. Trafic sécurisé.",
    location: "Devinette — la réponse est le code",
    points: 20,
    category: "CYBERSECURITY",
    difficulty: "medium",
  },
  {
    code: "WALTER-WHITE",
    name: "Célèbre série Break Bad",
    hint: "Say my name.",
    location: "Devinette — la réponse est le code",
    points: 20,
    category: "TV",
    difficulty: "medium",
  },
  {
    code: "WANNACRY",
    name: "Le rançongiciel qui s'est propagé tout seul en 2017",
    hint: "Il n'attendait pas qu'on clique : il utilisait une faille réseau volée à la NSA pour sauter d'une machine à l'autre, jusque dans les hôpitaux britanniques.",
    location: "Devinette — la réponse est le code",
    points: 20,
    category: "CYBERSECURITY-HISTORY",
    difficulty: "medium",
  },
  {
    code: "WEBSOCKET-RT",
    name: "Websocket communication temps réel",
    hint: "Bidirectionnel. Connexion persistante.",
    location: "Devinette — la réponse est le code",
    points: 30,
    category: "PROGRAMMING",
    difficulty: "hard",
  },
  {
    code: "WOMAN-CAT-MEME",
    name: "Meme woman pointing cat",
    hint: "Femme crie. Chat confus regarde.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "INTERNET-MEMES",
    difficulty: "easy",
  },
  {
    code: "WONDER-WOMAN",
    name: "Actrice super héros Wonder",
    hint: "Gal Gadot. Amazone. Lasso.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "MOVIES",
    difficulty: "easy",
  },
  {
    code: "YEET-MEME",
    name: "Héros qui dit YEET",
    hint: "Jeune. Tendance. Lancé loin.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "INTERNET-MEMES",
    difficulty: "easy",
  },
  {
    code: "YOUTUBE",
    name: "Plateforme vidéo red",
    hint: "Google. Partage. Monétisation.",
    location: "Devinette — la réponse est le code",
    points: 10,
    category: "TECH",
    difficulty: "easy",
  },
  {
    code: "ZERO-DAY",
    name: "La faille dont l'éditeur n'a pas encore entendu parler",
    hint: "Aucun correctif n'existe puisque personne ne sait qu'elle existe : d'où sa valeur sur le marché.",
    location: "Devinette — la réponse est le code",
    points: 30,
    category: "CYBERSECURITY",
    difficulty: "hard",
  },
  {
    code: "SIN-100-UNLOCK",
    name: "Deuxième palier",
    hint: "100 secrets trouvés. À mi-chemin de la fin. Accordé automatiquement.",
    location: "Palier automatique — 100 secrets trouvés",
    points: 50,
    category: "META",
    difficulty: "medium",
    unlockAt: 100,
  },
  {
    code: "SIN-FINAL-BOSS-ULTIMATE",
    name: "Le grand final",
    hint: "Trouve les 149 autres. Ce dernier vaut 150 points et s'accorde tout seul. Légende absolue.",
    location: "Palier automatique — 149 secrets trouvés",
    points: 150,
    category: "META",
    difficulty: "insane",
    badgeSlug: "legend",
    unlockAt: 149,
  },
  {
    code: "SIN-FIRST-UNLOCK",
    name: "Premier palier",
    hint: "50 secrets trouvés. Accordé automatiquement, en même temps que la légende.",
    location: "Palier automatique — 50 secrets trouvés",
    points: 50,
    category: "META",
    difficulty: "medium",
    unlockAt: 50,
  },
  {
    code: "SIN-LEGENDE",
    name: "La légende",
    hint: "Trouve 50 secrets. Celui-ci s'ouvre tout seul — il ne se tape pas.",
    location: "Palier automatique — 50 secrets trouvés",
    points: 50,
    category: "META",
    difficulty: "insane",
    badgeSlug: "secret",
    unlockAt: 50,
  },
]
