import "server-only"
import { mkdir, readFile, rm, writeFile } from "node:fs/promises"
import { join } from "node:path"

// Bind mount, NOT a named volume: Restic->B2 backs up ${DOCKERDIR}/appdata,
// not Docker volumes (see brutalist-lycee.yml, brutalist-web service, and
// the homelab repo for the compose diff). The container mounts the host
// path at /app/data/avatars; process.cwd() is /app in the standalone
// runtime image (see Dockerfile), so this resolves to the mounted path with
// zero extra config, and to <repo>/data/avatars for local dev (gitignored).
// AVATAR_DIR is still readable from the environment so tests and one-off
// scripts can point this at a throwaway directory instead.
const AVATAR_DIR = process.env.AVATAR_DIR || join(process.cwd(), "data", "avatars")

// Filenames are always generated by us (uploadAvatar uses randomUUID()),
// never derived from user input. This regex is defence in depth at the
// read/write boundary: even if a future code path ever passed through an
// unexpected `avatar_file` value, it could not be used to escape AVATAR_DIR.
const SAFE_FILENAME_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.webp$/i

function resolveAvatarPath(filename: string): string {
  if (!SAFE_FILENAME_RE.test(filename)) {
    throw new Error(`Refusing unsafe avatar filename: ${filename}`)
  }
  return join(AVATAR_DIR, filename)
}

/** Writes a re-encoded avatar under its generated filename, creating the directory if needed. */
export async function writeAvatarFile(filename: string, data: Buffer): Promise<void> {
  await mkdir(AVATAR_DIR, { recursive: true })
  await writeFile(resolveAvatarPath(filename), data)
}

/** Reads an avatar file, or null if it doesn't exist (already removed, or never written). */
export async function readAvatarFile(filename: string): Promise<Buffer | null> {
  try {
    return await readFile(resolveAvatarPath(filename))
  } catch {
    return null
  }
}

/** Deletes an avatar file. Safe to call on a file that's already gone. */
export async function deleteAvatarFile(filename: string): Promise<void> {
  await rm(resolveAvatarPath(filename), { force: true })
}
